# Generated by Django 6.1.1 on 2026-09-14 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nif', models.CharField(max_length=14, unique=True)),
                ('regime_iva', models.CharField(max_length=50)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MapeamentoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_contabilidade', models.CharField(max_length=20)),
                ('campo_agt', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mapeamento_contas',
            },
        ),
        migrations.CreateModel(
            name='DeclaracaoAGT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('nif', models.CharField(max_length=14)),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True)),
                ('regime_iva', models.CharField(max_length=50)),
                ('iva_liquidado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('iva_dedutivel', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('iva_apurado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('iva_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('iva_recuperar', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaracoes_agt', to='reconciliacao.empresa')),
            ],
            options={
                'db_table': 'agt_declaracoes',
                'ordering': ['-ano', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='Contabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('conta_codigo', models.CharField(max_length=20)),
                ('conta_descricao', models.CharField(max_length=200)),
                ('valor_debito', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_credito', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contabilidade', to='reconciliacao.empresa')),
            ],
            options={
                'db_table': 'contabilidade',
                'ordering': ['conta_codigo'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('data_reconciliacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CONCILIADO', 'Conciliado'), ('DIVERGENCIA', 'Divergência'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20)),
                ('total_campos_ok', models.IntegerField(default=0)),
                ('total_campos_divergencia', models.IntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliacoes', to='reconciliacao.empresa')),
            ],
            options={
                'db_table': 'reconciliacoes',
                'ordering': ['-ano', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliacaoDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('valor_contabilidade', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_agt', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('diferenca', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('DIVERGENCIA', 'Divergência')], max_length=20)),
                ('nivel', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reconciliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='reconciliacao.reconciliacao')),
            ],
            options={
                'db_table': 'reconciliacao_detalhes',
                'ordering': ['nivel', 'campo'],
            },
        ),
    ]
