# Generated by Django 6.1.1 on 2026-09-14 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('tipo', models.CharField(choices=[('CONTABILIDADE', 'Dados Contabilidade'), ('AGT', 'Portal AGT')], max_length=20)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('texto_extraido', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'documentos_upload',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documento_agt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_agt', to='reconciliacao.documentoupload')),
                ('documento_contabilidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_contab', to='reconciliacao.documentoupload')),
            ],
            options={
                'db_table': 'analises_ia',
                'ordering': ['-created_at'],
            },
        ),
    ]
