# Generated by Django 4.2.5 on 2026-09-29 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copiar_ativo_para_estado(apps, schema_editor):
    Empresa = apps.get_model('reconciliacao', 'Empresa')
    for empresa in Empresa.objects.all():
        if not empresa.ativo:
            empresa.estado = 'INATIVA'
            empresa.save(update_fields=['estado'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reconciliacao', '0002_documentoupload_analiseia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='atividade_principal',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cae_principal',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='comuna',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='data_constituicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='data_inicio_atividade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa'), ('SUSPENSA', 'Suspensa'), ('ENCERRADA', 'Encerrada')], default='ATIVA', max_length=15),
        ),
        migrations.AddField(
            model_name='empresa',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nome_comercial',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='provincia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_entidade',
            field=models.CharField(blank=True, choices=[('PS', 'Pessoa Singular'), ('ENI', 'Empresário em Nome Individual'), ('SQ', 'Sociedade por Quotas'), ('SA', 'Sociedade Anónima'), ('COOP', 'Cooperativa'), ('ASS', 'Associação'), ('FUND', 'Fundação'), ('OUTRO', 'Outro')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nif',
            field=models.CharField(error_messages={'unique': 'Já existe uma empresa registada com este NIF.'}, max_length=14, unique=True),
        ),
        migrations.RunPython(
            copiar_ativo_para_estado,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='ativo',
        ),
        migrations.CreateModel(
            name='EmpresaUtilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_acesso', models.CharField(choices=[('ADMIN', 'Administrador'), ('AUDITOR', 'Auditor'), ('CONTABILISTA', 'Contabilista'), ('FISCALISTA', 'Fiscalista'), ('ANALISTA', 'Analista'), ('CONSULTA', 'Consulta')], default='CONSULTA', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='reconciliacao.empresa')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empresa_utilizadores',
                'ordering': ['empresa', 'utilizador'],
                'unique_together': {('empresa', 'utilizador')},
            },
        ),
    ]
