# Generated by Django 6.1.1 on 2026-09-30 07:30

import django.db.models.deletion
from django.db import migrations, models


def preencher_documentos_legados(apps, schema_editor):
    DocumentoUpload = apps.get_model('reconciliacao', 'DocumentoUpload')
    Empresa = apps.get_model('reconciliacao', 'Empresa')
    mapa_tipos = {'CONTABILIDADE': 'BALANCETE', 'AGT': 'MODELO7'}
    primeira_empresa = Empresa.objects.order_by('id').first()

    for doc in DocumentoUpload.objects.all():
        alterado = False
        if doc.tipo in mapa_tipos:
            doc.tipo = mapa_tipos[doc.tipo]
            alterado = True
        if doc.empresa_id is None and primeira_empresa is not None:
            doc.empresa = primeira_empresa
            alterado = True
        if doc.ano is None and doc.created_at is not None:
            doc.ano = doc.created_at.year
            alterado = True
        if doc.mes is None and doc.created_at is not None:
            doc.mes = doc.created_at.month
            alterado = True
        if doc.estado == 'RECEBIDO':
            doc.estado = 'VALIDADO' if (doc.texto_extraido or '').strip() else 'PROCESSADO'
            alterado = True
        if alterado:
            doc.save(update_fields=['tipo', 'empresa', 'ano', 'mes', 'estado'])


def reverter_documentos_legados(apps, schema_editor):
    DocumentoUpload = apps.get_model('reconciliacao', 'DocumentoUpload')
    mapa_inverso = {'BALANCETE': 'CONTABILIDADE', 'MODELO7': 'AGT'}
    for doc in DocumentoUpload.objects.filter(tipo__in=mapa_inverso):
        doc.tipo = mapa_inverso[doc.tipo]
        doc.save(update_fields=['tipo'])


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliacao', '0003_remove_empresa_ativo_empresa_atividade_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoupload',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoupload',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='reconciliacao.empresa'),
        ),
        migrations.AddField(
            model_name='documentoupload',
            name='estado',
            field=models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PROCESSANDO', 'Processando'), ('PROCESSADO', 'Processado'), ('VALIDADO', 'Validado'), ('UTILIZADO', 'Utilizado na auditoria'), ('ERRO', 'Processamento falhou'), ('ILEGIVEL', 'Documento ilegível'), ('PERIODO_ERRADO', 'Período incorrecto'), ('TIPO_DESCONHECIDO', 'Tipo desconhecido')], default='RECEBIDO', max_length=20),
        ),
        migrations.AddField(
            model_name='documentoupload',
            name='mes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contabilista_contacto',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contabilista_nome',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='empresa',
            name='periodo_inicial_analise',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='reparticao_fiscal',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentoupload',
            name='tipo',
            field=models.CharField(choices=[('BALANCETE', 'Balancete'), ('MODELO7', 'Modelo 7 (IVA)'), ('FACTURA_VENDA', 'Facturas de Venda'), ('FACTURA_COMPRA', 'Facturas de Compra'), ('FOLHA_SALARIAL', 'Folha Salarial'), ('EXTRACTO_BANCARIO', 'Extracto Bancário'), ('RETENCOES', 'Retenções'), ('COMPROVATIVOS', 'Comprovativos de Pagamento'), ('IMPOSTO_INDUSTRIAL', 'Imposto Industrial'), ('DECLARACAO_IRT', 'Declaração de IRT'), ('FOLHA_SS', 'Folha Segurança Social'), ('OUTRO', 'Outro')], max_length=20),
        ),
        migrations.RunPython(preencher_documentos_legados, reverter_documentos_legados),
    ]
