# Generated by Django 6.1.1 on 2026-09-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliacao', '0004_documentoupload_ano_documentoupload_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoupload',
            name='tipo_sugerido',
            field=models.CharField(blank=True, choices=[('BALANCETE', 'Balancete'), ('MODELO7', 'Modelo 7 (IVA)'), ('FACTURA_VENDA', 'Facturas de Venda'), ('FACTURA_COMPRA', 'Facturas de Compra'), ('FOLHA_SALARIAL', 'Folha Salarial'), ('EXTRACTO_BANCARIO', 'Extracto Bancário'), ('RETENCOES', 'Retenções'), ('COMPROVATIVOS', 'Comprovativos de Pagamento'), ('IMPOSTO_INDUSTRIAL', 'Imposto Industrial'), ('DECLARACAO_IRT', 'Declaração de IRT'), ('FOLHA_SS', 'Folha Segurança Social'), ('OUTRO', 'Outro')], help_text='Classificação automática (Fase 2); o utilizador pode corrigir via "tipo".', max_length=20, null=True),
        ),
    ]
