# Generated by Django 6.1.1 on 2026-09-30 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliacao', '0005_documentoupload_tipo_sugerido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('regimes_aplicaveis', models.JSONField(blank=True, default=list)),
                ('implementacao', models.CharField(choices=[('PENDENTE', 'Por implementar'), ('PARCIAL', 'Implementação parcial'), ('ACTIVO', 'Activo')], default='PENDENTE', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'auditoria_motor',
                'ordering': ['ordem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='PerfilFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_fiscal', to='reconciliacao.empresa')),
                ('motores_aplicaveis', models.ManyToManyField(blank=True, related_name='perfis_fiscais', to='reconciliacao.motor')),
            ],
            options={
                'db_table': 'auditoria_perfil_fiscal',
            },
        ),
        migrations.CreateModel(
            name='DocumentoRequerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('BALANCETE', 'Balancete'), ('MODELO7', 'Modelo 7 (IVA)'), ('FACTURA_VENDA', 'Facturas de Venda'), ('FACTURA_COMPRA', 'Facturas de Compra'), ('FOLHA_SALARIAL', 'Folha Salarial'), ('EXTRACTO_BANCARIO', 'Extracto Bancário'), ('RETENCOES', 'Retenções'), ('COMPROVATIVOS', 'Comprovativos de Pagamento'), ('IMPOSTO_INDUSTRIAL', 'Imposto Industrial'), ('DECLARACAO_IRT', 'Declaração de IRT'), ('FOLHA_SS', 'Folha Segurança Social'), ('OUTRO', 'Outro')], max_length=20)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_requeridos', to='reconciliacao.motor')),
            ],
            options={
                'db_table': 'auditoria_documento_requerido',
                'ordering': ['motor__ordem', 'id'],
                'unique_together': {('motor', 'tipo_documento')},
            },
        ),
    ]
