# Generated by Django 6.1.1 on 2026-09-30 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliacao', '0006_motor_perfilfiscal_documentorequerido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legislacao', models.CharField(max_length=200)),
                ('artigo', models.CharField(max_length=200)),
                ('texto', models.TextField(blank=True, default='')),
                ('fonte_oficial', models.URLField(blank=True, default='')),
                ('vigencia_inicio', models.DateField(blank=True, help_text='Vazio = sem limite definido (pendente de validação jurídica).', null=True)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('validado_juridicamente', models.BooleanField(default=False)),
                ('validado_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_legal_validada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'regra_base_legal',
                'ordering': ['legislacao', 'artigo'],
            },
        ),
        migrations.CreateModel(
            name='Regra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('imposto', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('condicao', models.TextField(help_text='Expressão booleana com variáveis whitelisted do contexto.')),
                ('formula', models.TextField(blank=True, default='', help_text='Expressão que calcula o valor envolvido; vazio = 0.')),
                ('severidade', models.CharField(choices=[('INFORMATIVO', 'Informativo'), ('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto')], default='MEDIO', max_length=15)),
                ('recomendacao', models.TextField(blank=True, default='')),
                ('versao', models.PositiveIntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
                ('estado_validacao', models.CharField(choices=[('POR_VALIDAR', 'Por validar'), ('VALIDADA', 'Validada'), ('REJEITADA', 'Rejeitada')], default='POR_VALIDAR', max_length=15)),
                ('validado_em', models.DateTimeField(blank=True, null=True)),
                ('validacao_nota', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_legal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras', to='reconciliacao.baselegal')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras', to='reconciliacao.motor')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_validadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'regra_regra',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('severidade', models.CharField(choices=[('INFORMATIVO', 'Informativo'), ('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto')], max_length=15)),
                ('valor_envolvido', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('evidencia', models.JSONField()),
                ('recomendacao', models.TextField(blank=True, default='')),
                ('versao_regra', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('ABERTA', 'Aberta'), ('REVISADA', 'Revisada'), ('IGNORADA', 'Ignorada'), ('RESOLVIDA', 'Resolvida')], default='ABERTA', max_length=15)),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='reconciliacao.empresa')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_revisadas', to=settings.AUTH_USER_MODEL)),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='reconciliacao.regra')),
            ],
            options={
                'db_table': 'regra_ocorrencia',
                'ordering': ['-created_at'],
                'unique_together': {('empresa', 'ano', 'mes', 'regra')},
            },
        ),
    ]
